CREATE TABLE PERSON (
	PERSON_ID INT NOT NULL PRIMARY KEY,
	FIRST_NAME VARCHAR(40) NOT NULL,
	MIDDLE_NAME VARCHAR(40),
	LAST_NAME VARCHAR(40) NOT NULL,
	EMAIL VARCHAR(100)
);


CREATE TABLE ADDRESS (
	ADDRESS_ID INT NOT NULL PRIMARY KEY,
	PERSON_ID INT NOT NULL,
	STREET VARCHAR(80) NOT NULL,
	CITY VARCHAR(40) NOT NULL,
	STATE VARCHAR(40) NOT NULL,
	ZIP VARCHAR(10) NOT NULL
);

ALTER TABLE ADDRESS ADD FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID);
ALTER TABLE ADDRESS ADD CONSTRAINT ADDRESS_PERSON_ID_UNIQUE UNIQUE(PERSON_ID);


CREATE TABLE PHONE_TYPE (
	TYPE_CODE VARCHAR(6) NOT NULL PRIMARY KEY
);

INSERT INTO PHONE_TYPE (TYPE_CODE) VALUES('home');
INSERT INTO PHONE_TYPE (TYPE_CODE) VALUES('work');
INSERT INTO PHONE_TYPE (TYPE_CODE) VALUES('mobile');

CREATE TABLE PHONE (
	PHONE_ID INT NOT NULL PRIMARY KEY,
	PERSON_ID INT NOT NULL,
	NUMBER VARCHAR(12),
	TYPE VARCHAR(6) NOT NULL
);

ALTER TABLE PHONE ADD FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID);
ALTER TABLE PHONE ADD FOREIGN KEY (TYPE) REFERENCES PHONE_TYPE(TYPE_CODE);
ALTER TABLE PHONE ADD CONSTRAINT PERSON_PHONE_TYPE_UNIQUE UNIQUE(PERSON_ID, TYPE);


CREATE SEQUENCE PERSON_ID_SEQ
	INCREMENT BY 1
	MINVALUE 5001
	NOMAXVALUE;


CREATE SEQUENCE ADDRESS_ID_SEQ
	INCREMENT BY 1
	MINVALUE 5001
	NOMAXVALUE;

CREATE SEQUENCE EMAIL_ID_SEQ
	INCREMENT BY 1
	MINVALUE 5001
	NOMAXVALUE;

CREATE SEQUENCE PHONE_ID_SEQ
	INCREMENT BY 1
	MINVALUE 5001
	NOMAXVALUE;


-- EXAMPLE CONTACT
INSERT INTO PERSON (PERSON_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL)
		VALUES(1001, 'Harold', 'Francis', 'Gilkey', 'harold.gilkey@yahoo.com');

INSERT INTO ADDRESS (ADDRESS_ID, PERSON_ID, STREET, CITY, STATE, ZIP)
		VALUES(1001, 1001, '8360 High Autumn Row', 'Cannon', 'Delaware', '19797');

INSERT INTO PHONE (PHONE_ID, PERSON_ID, NUMBER, TYPE) VALUES(1001, 1001, '302-611-9148', 'home');
INSERT INTO PHONE (PHONE_ID, PERSON_ID, NUMBER, TYPE) VALUES(1002, 1001, '302-532-9427', 'mobile');
